"""add resume_parsed_data to user model

Revision ID: 71a05774a775
Revises: fd6ce52b5909
Create Date: 2024-12-15 14:22:24.969835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a05774a775'
down_revision = 'fd6ce52b5909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_parsed_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume_parsed_data')

    # ### end Alembic commands ###
